from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
import os
import uuid
from datetime import datetime

styles = getSampleStyleSheet()

title_style = styles["Title"]
title_style.alignment = TA_CENTER

heading_style = styles["Heading2"]
sub_heading_style = styles["Heading3"]
body_style = styles["BodyText"]


def divider(story):
    story.append(
        Paragraph(
            "<font color='grey'>────────────────────────────────────────────────────────</font>",
            body_style,
        )
    )
    story.append(Spacer(1, 10))


def add_section(story, title):
    story.append(Spacer(1, 12))
    divider(story)
    story.append(Paragraph(f"<b>{title}</b>", heading_style))
    story.append(Spacer(1, 8))


def add_field(story, title, value):
    story.append(Paragraph(f"<b>{title}</b>", sub_heading_style))

    if value is None:
        story.append(Paragraph("-", body_style))

    elif isinstance(value, list):
        if len(value) == 0:
            story.append(Paragraph("-", body_style))
        else:
            for item in value:
                story.append(Paragraph(f"• {item}", body_style))

    elif isinstance(value, dict):
        for k, v in value.items():
            story.append(
                Paragraph(f"<b>{k.replace('_',' ').title()}</b>", body_style)
            )

            if isinstance(v, list):
                for x in v:
                    story.append(Paragraph(f"• {x}", body_style))
            else:
                story.append(Paragraph(str(v), body_style))

    else:
        story.append(Paragraph(str(value), body_style))

    story.append(Spacer(1, 8))


def generate_project_report(project, analysis, research):

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/{uuid.uuid4().hex}.pdf"

    doc = SimpleDocTemplate(filename)

    story = []

    # =====================================================
    # HEADER
    # =====================================================

    story.append(Paragraph("PROJECT DORA", title_style))
    story.append(
        Paragraph(
            "<b>AI Project Discovery & Research Report</b>",
            heading_style,
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d %B %Y %I:%M %p')}",
            body_style,
        )
    )

    story.append(
        Paragraph(
            "<b>Version:</b> Project DORA v1.0",
            body_style,
        )
    )

    story.append(Spacer(1, 20))

    # =====================================================
    # PROJECT DETAILS
    # =====================================================

    add_section(story, "PROJECT DETAILS")

    add_field(story, "Project Title", project.get("Project Title"))
    add_field(story, "Description", project.get("Short Description"))
    add_field(story, "Difficulty", project.get("Difficulty"))
    add_field(story, "Innovation Score", project.get("Innovation Score"))
    add_field(story, "Resume Value", project.get("Resume Value"))
    add_field(story, "Interview Value", project.get("Interview Value"))
    add_field(
        story,
        "Estimated Development Time",
        project.get("Estimated Development Time"),
    )
    add_field(
        story,
        "Recommended Tech Stack",
        project.get("Recommended Tech Stack"),
    )
    add_field(
        story,
        "Major Modules",
        project.get("Major Modules"),
    )

    # =====================================================
    # ANALYSIS
    # =====================================================

    add_section(story, "AI PROJECT ANALYSIS")

    for key, value in analysis.items():
        add_field(
            story,
            key.replace("_", " ").title(),
            value,
        )

    # =====================================================
    # RESEARCH
    # =====================================================

    add_section(story, "AI RESEARCH REPORT")

    for key, value in research.items():
        add_field(
            story,
            key.replace("_", " ").title(),
            value,
        )

    # =====================================================
    # FOOTER
    # =====================================================

    story.append(Spacer(1, 25))

    divider(story)

    story.append(
        Paragraph(
            "<b>Generated by Project DORA</b>",
            heading_style,
        )
    )

    story.append(
        Paragraph(
            "AI Platform for Project Discovery, Research & Innovation Planning",
            body_style,
        )
    )

    doc.build(story)

    return filename